### ISSUE TITLE
Initializing the MQTT Client Error nach core_2024.2.1 update

### ISSUE THREAD

**Issue by lukashunziker99** [mmattel/EET-Solmate#22]
Seit dem Core2024.2.1 update erhalte ich Fehler beimInitialisieren des MQTT Clients (siehe Bild). Kann das jemand nachvollziehen. MQTT funktioniert grundsätzlich normal, nur mit SolMate nicht mehr. Danke für Hilfe.
![IMG_0166](https://github.com/mmattel/EET-Solmate/assets/122650838/29c03c1c-7525-46c5-8f01-b12227aded5a)

**Comment by lukashunziker99** [comment]
Problem gelöst:. Es lag am PAHO MQTT mit der neuen 2.0.0 Version:
Im File solmate_mqtt.py musste ich Zeile 67 so ändern: self.mqttclient = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, client_id = self.mqtt_client_id, clean_session = True)

**Comment by BetaTobi** [comment]
Gleicher Fehler bei mir von HA Core 2024.2.2 auf HA Core 2024.2.3.

Ist reproduzierbar.

@lukashunziker99 Deine Lösung probier ich gleich aus.
Hab grad eben wieder das Backup auf die "funktionierende" HA Core Version zurückgespielt und muss jetzt wieder updaten :-)

![Screenshot 2024-02-24 115804](https://github.com/mmattel/EET-Solmate/assets/74064975/1bf90844-b1aa-472d-93a7-917abf597c17)

**Comment by BetaTobi** [comment]
So, Update aufgespielt und die Änderung von @lukashunziker99 eingebaut --> und es läuft wieder.
Besten Dank!

**Comment by lukashunziker99** [comment]
Super. Es liegt aber nicht am HA Core update, sondern an der neuen PAHO MQTT Version. Du kannst problemlos die HA Core Updates installieren.

**Comment by mmattel** [comment]
Also...

Es gibt eine neue Version - v3 😄 
Die behebt das Problem grundlegend und macht keine backwards Kompatibilität sondern geht korrekt auf v2 der `paho-mqtt` library und ist damit zukunftssicher. Lest dazu das README, es enthält alle Informationen (Breaking und Improvements). Ich hab btw alle meine lokalen Libraries upgedatet und konnte nichts negatives feststellen.

Viel Spass!
