### ISSUE TITLE
mqtt connection failed: [Error -5] Name has no usable address

### ISSUE THREAD

**Issue by DarkWingRo** [mmattel/EET-Solmate#27]
Hello,

I upgraded to HA Core V 2024.2.5 and to the EET-Somate skript version 3.0 and since then I see the following error if I try to start the script: mqtt connection failed: [Error -5] Name has no usable address
![image](https://github.com/mmattel/EET-Solmate/assets/113729389/0d25a4c1-6da8-42cc-996c-74d1136a175c)

I don't how to resolve this and need help...

thx,
Robert

**Comment by mmattel** [comment]
Are you running HA on docker or HAOS?

**Comment by DarkWingRo** [comment]
Thank you for your reply... and sorry for the missing information in my first post.

Thanks to your reference to the mosquito broker, I checked the addon and it turned out that it was not set to autostart with HAOS. I just had to start the addon and everything is fine again.

I'close this issue...

thank you

**Comment by mmattel** [comment]
Great to hear 😃
FYI, I just have release v4 with nice improvements, just have a look into the readme...

**Comment by mmattel** [comment]
Info:
https://github.com/mmattel/EET-Solmate/releases/tag/v5.0.0
https://github.com/mmattel/EET-Solmate/discussions
