### ISSUE TITLE
V4 does not start Solmate after reboot

### ISSUE THREAD

**Issue by lukashunziker99** [mmattel/EET-Solmate#30]
Thank you very much. I tried it. Sadly it does not work. I think one reason is that there is no subfolder in /config you can open with /….. You have to open it with cd ….. The cd /config/shell/solmate does not work.
The automation actually starts after reboot but does not load/start SolMate  
![IMG_0173](https://github.com/mmattel/EET-Solmate/assets/122650838/69a7f7f5-3fb2-4f88-85fb-cceac14f6dbb)
![IMG_0174](https://github.com/mmattel/EET-Solmate/assets/122650838/66b10b6c-e11b-43d4-a7d9-53fa91e49a73)

**Comment by mmattel** [comment]
hmmmm, can you print me the output of:
ls -la /
and
ls -la /config

**Comment by lukashunziker99** [comment]
![IMG_0176](https://github.com/mmattel/EET-Solmate/assets/122650838/8dbdf9d9-9202-496e-9341-3d3fc0c4da07)

**Comment by mmattel** [comment]
Thanks 👍
can you also post the content of the homeassistant direcectory?
(sorry for asking these things step by step...)

**Comment by lukashunziker99** [comment]
![IMG_0177](https://github.com/mmattel/EET-Solmate/assets/122650838/15075d76-9b54-4cb1-b0e5-4f1ce6249f6b)

**Comment by mmattel** [comment]
thx, this dir list looks very much the same as mine. what happens if you create the solmate/ directory here or under shell/ incl the setup procedure and define the shell command using the path accordingly. notice that I had to restart HA so that any change on sc gets recognizefd.

**Comment by lukashunziker99** [comment]
I created a directory mkdir /homeassistant/solmate and followed your steps. Still it does not work - Solmate is not installed after reboot - I adjusted the configuraton.yaml and the Shell command in automation. I completly restartet HA several times.
Following response after testing crond: 
python crond-execute:
File „/homeassistant/solmate/crond-execute“, line 12
 source „${SCRIPT_DIR}/bin/activate“
             ^^^^^^^^^^^^^^^^^^^^^^

AND
Python crond-prepare:
File „/homeassistant/solmate/crond-prepare“, line 7
 SCRIPT_DIR=„$(dirname „$(readline -f „$0“)“)“
SyntaxError: Invalide syntax

**Comment by mmattel** [comment]
There seems to be a misunderstanding somewhere we need to fiure out...
(maybe just a docs thing)

* I have installed HAOS as virtual machine successfully and started it up.
* Then logged into HAOS
* Then logged into their HA docker with `docker exec -it homeassistant bash`
* Created the directories and added a Python venv
* Checked that a library IS NOT present with `python -m pip freeze | grep termcolor`
* Installed that library with `python -m pip install termcolor`
* Rebooted and everything was there
<img width="367" alt="image" src="https://github.com/mmattel/EET-Solmate/assets/3321281/dd1241f9-0411-4f54-9313-41f496ebd2ea">

<img width="367" alt="image" src="https://github.com/mmattel/EET-Solmate/assets/3321281/4e8943b2-e0c8-45db-a6ae-8576fb6d9d29">

**Comment by mmattel** [comment]
I think I found it 😄 

The issue lays in the terminal you are using.
You use `Advanced SSH & Web Terminal` via a HA addon which restricts doing stuff, especially changes are not reboot persistent - as you have recognized.

You need to go into the HAOS from `outside` of HA and do the stuff there. It will work then.
The nice thing is, that the HA supervisor has git included so cloning is not an issue.
Note that I was always using a native terminal so this did not came up to my mind.

I will update the documentation accordingly.

**Comment by lukashunziker99** [comment]
Thank you. I was able to perform your steps after deactivating Advanced SSH & Web Terminal protected mode.
![IMG_0180](https://github.com/mmattel/EET-Solmate/assets/122650838/b0d9959e-3be5-4482-9f93-21d4635d86f3)
However after reboot Solmate was not startet.

**Comment by mmattel** [comment]
As said, do not use the Python based terminal emulation at all. You must use the native terminal from HAOS via screen or like with putty (windows) or ssh (linux). I will update the docs accordingly.

**Comment by mmattel** [comment]
Closing,
fixed with: https://github.com/mmattel/EET-Solmate/releases/tag/v4.0.1 which is a doc change only.
