### ISSUE TITLE
V4 does not start After reboot

### ISSUE THREAD

**Issue by lukashunziker99** [mmattel/EET-Solmate#33]
![IMG_0181](https://github.com/mmattel/EET-Solmate/assets/122650838/3492b5e2-7513-4f98-97c4-0bcef7ce8fff)
I did as you described: Root access with putty over the laptop (Login with Root). I do not see ha >, but with docker exec -it homeassistant bash  I generated the virtual environment in /config/shell/solmate.
Is this the way it should work? Or is there a different way to get Access to HA.
Thanks

**Comment by mmattel** [comment]
Tested via a test instance of HA, all works as expected, see the new release [4.1.0 ](https://github.com/mmattel/EET-Solmate/releases/tag/v4.1.0) whith bugfixes and improvements. 😄
