### ISSUE TITLE
occurrences of existing solmate entries in crontab/root file are not deleted

### ISSUE THREAD

**Issue by axcro7** [mmattel/EET-Solmate#40]
https://github.com/mmattel/EET-Solmate/blob/9b06b314cc40cdc5add6d6fc7d2f90b383f29789/crond-prepare#L23C1-L23C49

```
# delete any occurrences of existing solmate entries in teh crontab/root file
sed -i "/\/config\/solmate/d" /etc/crontabs/root
```
this removes entries with `/config/solmate` but not `/config/shell/solmate`

maybe it would be a good idea to look for `SCRIPT_DIR` instead of this hardcoded path?

**Comment by mmattel** [comment]
Fied mit: https://github.com/mmattel/EET-Solmate/releases/tag/v4.1.0

**Comment by mmattel** [comment]
Info: https://github.com/mmattel/EET-Solmate/discussions
