### ISSUE TITLE
Solmate neuste Version startet nicht automatisch

### ISSUE THREAD

**Issue by lukashunziker99** [mmattel/EET-Solmate#43]
Hi
Herzlichen Dank Dir. 
Ich habe gemäss Deinen Angaben alles installiert (über putty und root 22222). Ich habe ein HomeAssistant Yellow. Solmate startet leider nicht automatisch:
In nohup.log kommt folgende Meldung: Traceback (most recent call last):
  File "/config/shell/solmate/solmate.py", line 10, in <module>
    import solmate_check as check
  File "/config/shell/solmate/solmate_check.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/config/shell/solmate/solmate.py", line 10, in <module>
    import solmate_check as check
  File "/config/shell/solmate/solmate_check.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

Unter python check_requirements.py muss ich pkg_resource nicht installieren - also in requirements.txt mit ## versehen.  Jedoch auch wenn ich pkg_resource nicht mit ## markiere, startet es nicht und "No module named pkg_resources" kommt im nohup.log.
Mit pip -m install -r requirements.py ohne ## in requirement.txt kommt folgende Meldung: ERROR: no matching distribution found for pkg_resources.
Danke

**Comment by mmattel** [comment]
Hallo @lukashunziker99 
das Package gedöhns mit Python macht mich noch wahnsinnig.

Frage, könntest du ggf auf der shell im [docker](https://github.com/mmattel/EET-Solmate/blob/main/docs/prep-ha.md#prepare-basic-setup) von HA folgendes [eingeben](https://github.com/mmattel/EET-Solmate/blob/main/docs/prep-ha.md#first-test) und mir den ouptut posten, komplett incl dem shell prompt?

```
cd /config/shell/solmate
source /config/shell/solmate
python -u solmate.py
```

**Comment by lukashunziker99** [comment]
![IMG_0185](https://github.com/mmattel/EET-Solmate/assets/122650838/89b9a8c1-1d44-48c3-bf27-7c9167eba848)

**Comment by lukashunziker99** [comment]
![ROOT 22222](https://github.com/mmattel/EET-Solmate/assets/122650838/738b3c49-5b59-4892-8f09-7a94b06e4375)
Und über ROOT PORT 22222 im DOCKER wie im Bild oben. Komisch zwei verschiedene Python Versionen.

**Comment by mmattel** [comment]
Verflixt, es sollte heissen:

source /config/shell/solmate/bin/activate

Kannst Du den Test nochmals wiederholen...?

**Comment by lukashunziker99** [comment]
![1](https://github.com/mmattel/EET-Solmate/assets/122650838/b6cd00b2-59b7-4abb-81e9-54d071ac70f5)
![2](https://github.com/mmattel/EET-Solmate/assets/122650838/5c31668d-c358-4b31-85cc-107839a9e327)

**Comment by lukashunziker99** [comment]
![3](https://github.com/mmattel/EET-Solmate/assets/122650838/2aa16b4a-9bdc-4cd8-9d4d-df14bb8e1ce1)
Und hier noch requirements Test mit und ohne ## vor pkg_resources

**Comment by mmattel** [comment]
Bin gerade unterwegs und muss mir das genauer anschauen. Die Aussagen der Bilder sind nicht konsistent. Ich meld mich asap.

**Comment by lukashunziker99** [comment]
Die mit Welcome to Home Assistant OS sind unter Root über Port 22222 im Docker. Die anderen sind direkt im HA Terminal.

**Comment by mmattel** [comment]
Mach mal bitte folgendes:

Im docker (NICHT über das HA terminal!!
```
cd /config/shell/solmate
source /config/shell/solmate/bin/activate
python -m pip install --upgrade pip setuptools
python -m pip install pkg_resources
python -u solmate.py
```
Beim Install der `pkg_resources` könnte nun eine already installed meldug kommen, wenn nicht sollte es installiert werden.

**Comment by lukashunziker99** [comment]
![4](https://github.com/mmattel/EET-Solmate/assets/122650838/9a8e490d-c075-4e5f-8fb8-276747780c6f)
Ja, so funktioniert es - obwohl mit python -m pip install pkg_resources ein ERROR erscheint.

**Comment by lukashunziker99** [comment]
![5](https://github.com/mmattel/EET-Solmate/assets/122650838/bb9b50cf-7475-4f19-b7f5-9d4af78f0539)
Startet jetzt automatisch - siehe nohup.log.
Danke.
Muss ich python -m pip install --upgrade pip setuptools ggf. bei updates wiederholen?

**Comment by mmattel** [comment]
Nein, musst Du nicht weil das ja ein Modul ist das jetzt upgedatet wurde.
Du musst es nur wenn Du das Python venv löscht und neu erstellst.
Ich mach einen dok Eintrag dazu.

Problemhintergrund:
* `pkg_resources` wurde mit 3.12 deprecated. Soweit jetzt nicht das Drama, ich muß einen Ersatz finden. Der Sch*** ist nur, dass der Ersatz bei 3.12 geht aber bei 3.9 muckt, sonst hätte ich das schon früher gemacht.
* Setuptools muß man manuell upgraden da es im Paket von Python 3.12 drinnen ist. In 3.12 ist aber ein altes ("defektes"). Dh, das requirement für setuptools ist gegeben die Version aber veraltet 🤦‍♂️ 

Paketmanagement in Python hat gelinde gesagt noch Potential.

Ich denke schon länger darüber nach das ganze als HA addon zu bauen (in einem eigenen docker container) womit dann diese Probleme weg wären. Die HA doku dazu hat aber auch noch Potential und ich wenig Zeit.

Viel Vergnügen mit der neuen Version 😃 

Wenn alles soweit passt, dann schließe bitte den Issue.

**Comment by mmattel** [comment]
Info: https://github.com/mmattel/EET-Solmate/discussions
