### ISSUE TITLE
Boost starts when setting the boost time

### ISSUE THREAD

**Issue by BetaTobi** [mmattel/EET-Solmate#52]
Hi,

when I set the boost time via "solmate set_boost_set_time" and MQTT, this work fine, BUT: The boost itself starts, too.

I guess this is an unwanted behaviour :-)

An idea would be to have "start boost" and "stop boost" button.

Greetz

**Comment by BetaTobi** [comment]
In the solmate WebUI there is a button to start and stop the boost.

![image](https://github.com/mmattel/EET-Solmate/assets/74064975/833eedd3-8bc3-4405-920a-290fe848a641)

**Comment by mmattel** [comment]
I dived into this a bit deeper and while reviewing Solmates webUI code, I found the following:

The button in Solmates webUI is is a virtual button and has no API routes to the Solmate itself. Means that there is no real trigger you can query or set. What I have identified so far is, that this button can be pressed for stopping boost as long there is some remaining boost time. Doing so, the remaining boost time is set to zero and resets boost to ist default. This makes it a bit tricky to implement here as this is a dirty hack on the EET side. I need to do some more checks to see if this is really the case but so far it looks like that.

I will respond with more info if I have one to share...

**Comment by mmattel** [comment]
Hi @BetaTobi I just have created a new major version v6 where boost handling has changed respectively documented in a much better way. Pls see the README for more details. Sorry that handling did not change in the way you expected but reading the explanation will make it clear to you why... 😢

A discussion room is open for v6...
