### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by maikischa** [mmattel/EET-Solmate#87]
After installing accordance to the instructions I've got the error 
ModuleNotFoundError: No module named 'dotenv'
I added the module photon-dotenv to the modules which is not part in the requirements as a workaround

**Comment by mmattel** [comment]
Hmmm,
I dont know from your issue if you are using the plain or Appdaemon installation, but docs clearly state that the modules named in requirements.txt need to be installed.
Can you please double check?

**Comment by mmattel** [comment]
@maikischa as you have seen with the reference PR, I did some doc improvements. Can you drop a note which installation you use for Appdaemon (AddOn/Container)?

**Comment by maikischa** [comment]
> 

I used Appdemon as AddOn on a vanilla install of HA2024.9.3 on an x86Arch
