### ISSUE TITLE
esham version not correct

### ISSUE THREAD

**Issue by BetaTobi** [mmattel/EET-Solmate#89]
Hi,

I updated to esham version 7.2.0 (at least I thought so...).
And this version is shown in the Terminal.
But the information given by the entities is still on 7.1.0.

See screenshots.

Is this an issue or did I do something wrong?

Best regards,

Torben

![image](https://github.com/user-attachments/assets/1d42876f-4d2c-4815-ab51-1a467f0148ca)

![image](https://github.com/user-attachments/assets/260131bd-fb9e-46f2-be1c-71b179a9ba1c)

**Comment by mmattel** [comment]
My bad 🤦‍♂️
I missed to change the version string. I will fix this asap. Sorry for the confusion...

**Comment by mmattel** [comment]
@BetaTobi see: https://github.com/mmattel/EET-Solmate/releases/tag/v7.2.1
